### ISSUE TITLE
not work.

### ISSUE THREAD

**Issue by Rafawell** [SystemStack/ez-funimation-dl#5]
It doesn't work for me, I think I must be doing something very wrong.
I do not know what is happening😥

------------------------------------------------------------------------------
@ F:\Downloader-nx\ez-funimation-dl-master

> npm run start

> ez-funimation-dl@1.0.0 start
> node dist/index.js

┌──────────────────────┬──────────────┐
│       (index)        │    Values    │
├──────────────────────┼──────────────┤
│   AudioPreference    │  'Japanese'  │
│  SubtitlePreference  │ 'Portuguese' │
│ BackgroundPreference │    false     │
└──────────────────────┴──────────────┘
√ Search Funimation🔎 ... soul
√ Which one is right? (autocomplete or arrow keys) » Soul Eater
√ Select seasons » Season 1
DOWNLOADING 26 episodes please wait
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}

@ F:\Downloader-nx\ez-funimation-dl-master

> npm install

up to date, audited 292 packages in 4s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

@ F:\Downloader-nx\ez-funimation-dl-master

> npm run build

> ez-funimation-dl@1.0.0 build
> npx webpack

asset index.js 8.58 KiB [compared for emit] [minimized] (name: main)
cacheable modules 16.1 KiB
  ./src/index.ts 2.72 KiB [built] [code generated]
  ./src/download.service.ts 1.28 KiB [built] [code generated]
  ./src/episode.service.ts 3.02 KiB [built] [code generated]
  ./src/search.ts 1.12 KiB [built] [code generated]
  ./src/user.ts 2.29 KiB [built] [code generated]
  ./src/access.ts 1.6 KiB [built] [code generated]
  ./src/service.ts 1.66 KiB [built] [code generated]
  ./src/config.ts 2.37 KiB [built] [code generated]
external "prompts" 42 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]
external "https" 42 bytes [built] [code generated]
external "node-fetch" 42 bytes [built] [code generated]
external "fs/promises" 42 bytes [built] [code generated]
webpack 5.50.0 compiled successfully in 2901 ms

@ F:\Downloader-nx\ez-funimation-dl-master

> npm run start

> ez-funimation-dl@1.0.0 start
> node dist/index.js

┌──────────────────────┬──────────────┐
│       (index)        │    Values    │
├──────────────────────┼──────────────┤
│   AudioPreference    │  'Japanese'  │
│  SubtitlePreference  │ 'Portuguese' │
│ BackgroundPreference │    false     │
└──────────────────────┴──────────────┘
√ Search Funimation🔎 ... soul
√ Which one is right? (autocomplete or arrow keys) » Soul Eater
√ Select seasons » Season 1
DOWNLOADING 26 episodes please wait
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}

@ F:\Downloader-nx\ez-funimation-dl-master

> npm install terser

up to date, audited 292 packages in 2s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

@ F:\Downloader-nx\ez-funimation-dl-master

> npm install node-fetch

up to date, audited 292 packages in 1s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

@ F:\Downloader-nx\ez-funimation-dl-master

> npm install

up to date, audited 292 packages in 1s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

@ F:\Downloader-nx\ez-funimation-dl-master

> npm run build

> ez-funimation-dl@1.0.0 build
> npx webpack

asset index.js 8.58 KiB [compared for emit] [minimized] (name: main)
cacheable modules 16.1 KiB
  ./src/index.ts 2.72 KiB [built] [code generated]
  ./src/download.service.ts 1.28 KiB [built] [code generated]
  ./src/episode.service.ts 3.02 KiB [built] [code generated]
  ./src/search.ts 1.12 KiB [built] [code generated]
  ./src/user.ts 2.29 KiB [built] [code generated]
  ./src/access.ts 1.6 KiB [built] [code generated]
  ./src/service.ts 1.66 KiB [built] [code generated]
  ./src/config.ts 2.37 KiB [built] [code generated]
external "prompts" 42 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]
external "https" 42 bytes [built] [code generated]
external "node-fetch" 42 bytes [built] [code generated]
external "fs/promises" 42 bytes [built] [code generated]
webpack 5.50.0 compiled successfully in 2825 ms

@ F:\Downloader-nx\ez-funimation-dl-master

> npm run start

> ez-funimation-dl@1.0.0 start
> node dist/index.js

┌──────────────────────┬──────────────┐
│       (index)        │    Values    │
├──────────────────────┼──────────────┤
│   AudioPreference    │  'Japanese'  │
│  SubtitlePreference  │ 'Portuguese' │
│ BackgroundPreference │    false     │
└──────────────────────┴──────────────┘
√ Search Funimation🔎 ... mushoku
√ Which one is right? (autocomplete or arrow keys) » Mushoku Tensei: Jobless Reincarnation
√ Select seasons » Season 2
DOWNLOADING 11 episodes please wait
node:fs:1334
  handleErrorFromBinding(ctx);
  ^

Error: EINVAL: invalid argument, mkdir './Videos/Mushoku Tensei: Jobless Reincarnation'
    at Object.mkdirSync (node:fs:1334:3)
    at r (F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2580)
    at F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2679
    at Array.map (<anonymous>)
    at Object.t.DownloadVideos (F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2664)
    at F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:5724
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4071,
  syscall: 'mkdir',
  code: 'EINVAL',
  path: './Videos/Mushoku Tensei: Jobless Reincarnation'
}

@ F:\Downloader-nx\ez-funimation-dl-master

> npm run dev

> ez-funimation-dl@1.0.0 dev
> npx webpack && node dist/index.js

asset index.js 8.58 KiB [compared for emit] [minimized] (name: main)
cacheable modules 16.1 KiB
  ./src/index.ts 2.72 KiB [built] [code generated]
  ./src/download.service.ts 1.28 KiB [built] [code generated]
  ./src/episode.service.ts 3.02 KiB [built] [code generated]
  ./src/search.ts 1.12 KiB [built] [code generated]
  ./src/user.ts 2.29 KiB [built] [code generated]
  ./src/access.ts 1.6 KiB [built] [code generated]
  ./src/service.ts 1.66 KiB [built] [code generated]
  ./src/config.ts 2.37 KiB [built] [code generated]
external "prompts" 42 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]
external "https" 42 bytes [built] [code generated]
external "node-fetch" 42 bytes [built] [code generated]
external "fs/promises" 42 bytes [built] [code generated]
webpack 5.50.0 compiled successfully in 2891 ms
┌──────────────────────┬──────────────┐
│       (index)        │    Values    │
├──────────────────────┼──────────────┤
│   AudioPreference    │  'Japanese'  │
│  SubtitlePreference  │ 'Portuguese' │
│ BackgroundPreference │    false     │
└──────────────────────┴──────────────┘
√ Search Funimation🔎 ... mushoku
√ Which one is right? (autocomplete or arrow keys) » Mushoku Tensei: Jobless Reincarnation
√ Select seasons » Season 2
DOWNLOADING 11 episodes please wait
node:fs:1334
  handleErrorFromBinding(ctx);
  ^

Error: EINVAL: invalid argument, mkdir './Videos/Mushoku Tensei: Jobless Reincarnation'
    at Object.mkdirSync (node:fs:1334:3)
    at r (F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2580)
    at F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2679
    at Array.map (<anonymous>)
    at Object.t.DownloadVideos (F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:2664)
    at F:\Downloader-nx\ez-funimation-dl-master\dist\index.js:1:5724
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4071,
  syscall: 'mkdir',
  code: 'EINVAL',
  path: './Videos/Mushoku Tensei: Jobless Reincarnation'
}

@ F:\Downloader-nx\ez-funimation-dl-master

>
------------------------------------------------------------------------------------------------

**Comment by Rafawell** [comment]
I wanted to use this one because it uses token🙂
